KILTprotocol/kilt-node

- README.md
> Documentation: Improve Readme and add Whitepaper Node Implementation Notes

- runtime/src/lib.rs
- runtime/src/portablegabi.rs
> feat: portablegabi

- start-node.sh
Build didn't go through because of missing telemetry verbosity. I set it to the highest value. Let's try the deploy again!? 😅
> fix: chainsetup 2

- src/chain_spec.rs
This we change our based unit to femto, the endowed accounts need more tokens.
- Check balance of faucet
> feat: give endowed accounts more tokens

- Cargo.lock
- Cargo.toml
- runtime/Cargo.toml
- runtime/build.rs
- runtime/src/attestation/mod.rs
- runtime/src/attestation/tests.rs
- runtime/src/ctype/mod.rs
- runtime/src/ctype/tests.rs
- runtime/src/delegation/mod.rs
- runtime/src/delegation/tests.rs
- runtime/src/did/mod.rs
- runtime/src/did/tests.rs
- runtime/src/error/mod.rs
- runtime/src/lib.rs
- runtime/src/portablegabi.rs
- src/chain_spec.rs
- src/command.rs
- src/service.rs
> update to substrate 2.0.0-rc5

- README.md
> Add Build on Substrate Badge

- README.md
Just some notes about the runtime upgrade
> docs: runtime upgrade

- README.md
updated how to build the standalone node
> fix readme after merge

- pallets/delegation/src/lib.rs
Adjusts the max_depth parameter in revoke_delegation so that it is equal to the number of levels you need to walk up to find the node owned by the sender of the tx.
**Examples:**
- when sender is owner of the current node, `max_depth=0`
- when sender is owner of the parent node, `max_depth=1`
Also renamed the param in is_delegating to `max_lookups`, as that's what it counts - not depth, which may have led to the issue in the first place.
?
> chore: adjusted max_depth parameter in revoke_delegation

- pallets/attestation/src/lib.rs
- pallets/attestation/src/migration.rs
- pallets/delegation/src/lib.rs
- pallets/delegation/src/migration.rs
- pallets/delegation/src/tests.rs
- pallets/did/src/lib.rs
- pallets/did/src/migration.rs
- runtimes/parachain/src/lib.rs
- runtimes/standalone/src/lib.rs
Prepare for a runtime upgrade.
- Setup a local chain with the old runtime (from version 0.23)
- Do a runtime upgrade using the wasm from this branch
> feat: runtime migrations

- nodes/parachain/src/cli.rs
- nodes/parachain/src/command.rs
- nodes/parachain/src/service.rs
- nodes/standalone/src/service.rs
- pallets/attestation/src/lib.rs
- pallets/ctype/src/lib.rs
- pallets/delegation/src/lib.rs
- pallets/did/src/lib.rs
- primitives/src/constants.rs
- primitives/src/lib.rs
- runtimes/parachain/src/lib.rs
- runtimes/standalone/src/lib.rs
* Add clippy allowance to all pallets and runtimes to temporarily fix clippy issues from Substrate macros
* Note: It's not required for all pallets but DID in the current state of develop but will be required once we merge #141 in which we upgrade the pallets to frame v2
* Fix other clippy warnings
* Move constants from parachain runtime to primitives as also done in #129 
CI pipeline for clippy should go green
> fix: clippy

- scripts/spec.sh
> feat: add fast gov peregrine spec

- scripts/peregrine_kilt.py
- scripts/spiritnet_kilt.py
- scripts/westend_kilt.py
> fix: update network info

- runtimes/parachain/src/lib.rs
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/src/lib.rs
> chore: bump runtime version to test runtime upgrade

- pallets/did/src/did_details.rs
- pallets/kilt-launch/src/lib.rs
- pallets/parachain-staking/src/lib.rs
- pallets/parachain-staking/src/tests.rs
- pallets/parachain-staking/src/types.rs
* fixes incorrect check for delegations per round
* replaces some unchecked conversions
> fix: delegation counter

- .editorconfig
- .gitlab-ci.yml
- .maintain/reset-spec/peregrine_kilt.py
- .maintain/reset-spec/peregrine_relay.py
- .maintain/reset-spec/peregrine_stg_kilt.py
- .maintain/reset-spec/peregrine_stg_relay.py
- README.md
- dev-specs/kilt-parachain/kilt-westend.json
- dev-specs/kilt-parachain/peregrine-kilt.json
- dev-specs/kilt-parachain/peregrine-relay.json
- dev-specs/kilt-parachain/peregrine-stg-kilt.json
- nodes/parachain/src/chain_spec.rs
- nodes/parachain/src/chain_spec/spiritnet.rs
- pallets/parachain-staking/src/default_weights.rs
* ci: always run pipelines. 😢 The changes where not detected correctly
> feat: add bootnodes&telemetry to chain spec

- Cargo.lock
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- pallets/attestation/Cargo.toml
- pallets/ctype/Cargo.toml
- pallets/delegation/Cargo.toml
- pallets/did/Cargo.toml
- pallets/parachain-staking/Cargo.toml
- pallets/parachain-staking/src/lib.rs
- pallets/parachain-staking/src/migrations.rs
- pallets/parachain-staking/src/migrations/v5.rs
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/Cargo.toml
- runtimes/standalone/src/lib.rs
> fix: Collator Storage

- nodes/parachain/src/chain_spec/spiritnet.rs
> fix: fill council&committee

- Cargo.lock
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- pallets/attestation/Cargo.toml
- pallets/crowdloan/Cargo.toml
- pallets/ctype/Cargo.toml
- pallets/delegation/Cargo.toml
- pallets/did/Cargo.toml
- pallets/kilt-launch/Cargo.toml
- pallets/pallet-did-lookup/Cargo.toml
- pallets/pallet-inflation/Cargo.toml
- pallets/parachain-staking/Cargo.toml
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/Cargo.toml
- runtimes/standalone/src/lib.rs
- support/Cargo.toml
> version 1.3.0

- .gitlab-ci.yml
- Dockerfile
- runtimes/common/src/constants.rs
- runtimes/peregrine/src/lib.rs
- runtimes/peregrine/src/tests.rs
- runtimes/spiritnet/src/lib.rs
- runtimes/spiritnet/src/tests.rs
- runtimes/standalone/src/lib.rs
> feat: calculate storage deposits based on storage usage

- .gitlab-ci.yml
> ci: rename registry

- .gitlab-ci.yml
> ci: change docker pull policy

- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/src/lib.rs
@weichweich @wischli maybe we can squeeze it in with the batch origin hotfix.
NOTE this is targeting `master`.
> fix: add force_batch to allowed DID calls

- .maintain/docker-auth-config.sh
> fix: disable curl output

- .gitlab-ci.yml
> chore: update srtool

- .github/workflows/add-ticket-to-weekly.yml
It fixes the second action that is triggered after a new ticket is created by kiltbot.
> fix: more CI actions

- .github/workflows/polkadot-version-upgrade-ticket.yml
> fix: multiline input for issue-bot

- Cargo.lock
- runtimes/common/src/constants.rs
- runtimes/spiritnet/src/lib.rs
created a new collectives for tippers.
> feat: create a tipper committee

- Cargo.lock
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- pallets/attestation/Cargo.toml
- pallets/ctype/Cargo.toml
- pallets/delegation/Cargo.toml
- pallets/did/Cargo.toml
Remove some unnecessary dependencies from some Cargo.toml files.
> chore: fix Cargo.toml files

- .github/workflows/semantic-pr-title.yml
See ticket.
If tests pass we're good!
> ci: update action in gh wf that was still using node12

- pallets/attestation/src/lib.rs
- pallets/ctype/src/lib.rs
- pallets/delegation/src/lib.rs
- pallets/did/src/lib.rs
- pallets/pallet-did-lookup/src/lib.rs
- pallets/pallet-web3-names/src/lib.rs
- pallets/parachain-staking/src/lib.rs
- pallets/public-credentials/src/lib.rs
Just remove some unnecessary comments…
> refactor: remove 'No fail beyond' comments

- .gitlab-ci.yml
Reverts KILTprotocol/kilt-node#459
Reverts until stable toolchain supporter
> Revert "chore: publish metadata as gitlab artifact"

- pallets/parachain-staking/src/lib.rs
- pallets/parachain-staking/src/tests.rs
Fixes https://github.com/KILTprotocol/ticket/issues/2406.
Tests have been extended to check for one more year of rewards.
> feat: extend delegation rewards into Y3

- pallets/parachain-staking/src/lib.rs
- pallets/parachain-staking/src/tests.rs
Just reverted the [PR](https://github.com/KILTprotocol/kilt-node/pull/518) from Antonio and changed it slightly. 
> feat: delegation reward

- .gitlab-ci.yml
- Upgrade srtool
- Extract metada and publish as artifact
> ci: generate metadata with subwasm

- Cargo.lock
- Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/src/lib.rs
* update proxy type for multisig pallet
* bring runtimes in sync
* update version to 1.11.0-rc0
**NOTE**: this merges into release-1.11.0
> chore: prepare release

- scripts/diff-runtimes.sh
* first step to check runtimes diff with each PR
* This could be formed into a CI at some point
> feat: diff runtimes

- .github/PULL_REQUEST_TEMPLATE.md
- .gitlab-ci.yml
Merged with too much confidence... 😞 
[Pipeline works](https://gitlab.com/kiltprotocol/kilt-node/-/pipelines/1019820449)
> ci: fix try-runtime build

- pallets/did/src/did_details.rs
- pallets/pallet-did-lookup/src/migrations.rs
- runtimes/common/src/migrations.rs
- runtimes/kestrel/src/lib.rs
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/src/lib.rs
- scripts/diff-runtimes.sh
<details>
```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
No change detected
SUMMARY:
- Compatible.......................: true
- Require transaction_version bump.: false
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
```
</details>
<details>
<summary>Spiritnet Diff</summary>
```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
No change detected
SUMMARY:
- Compatible.......................: true
- Require transaction_version bump.: false
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
```
</details>
> chore: remove old migrations

- .github/workflows/polkadot-version-upgrade-ticket.yml
> fix: Replace archived repos with new polkadot-sdk repo

- nodes/parachain/src/cli.rs
* related https://github.com/KILTprotocol/ticket/issues/2522
<details>
```
```
</details>
<details>
<summary>Spiritnet Diff</summary>
```
```
</details>
> fix: prevent panic

- pallets/pallet-dip-provider/README.md
As discussed https://github.com/KILTprotocol/docs/pull/291#discussion_r1457061411
> chore: update README.md to fix typo

- .gitlab-ci.yml
https://gitlab.com/kiltprotocol/kilt-node/-/jobs/6645529528 ops...
> fix: try-runtime pipelines

- pallets/pallet-dip-consumer/README.md
- pallets/pallet-dip-provider/README.md
Docs: Tweaks some grammar and readability to the DIP pallet readmes so they can be included in docs.
> docs: Bring docs changes into DIP read me files

- pallets/pallet-asset-switch/src/benchmarking.rs
- pallets/pallet-asset-switch/src/lib.rs
- pallets/pallet-asset-switch/src/mock.rs
- pallets/pallet-asset-switch/src/tests/force_set_switch_pair.rs
- pallets/pallet-asset-switch/src/tests/force_unset_switch_pair.rs
- pallets/pallet-asset-switch/src/tests/mod.rs
- pallets/pallet-asset-switch/src/tests/pause_switch_pair.rs
- pallets/pallet-asset-switch/src/tests/resume_switch_pair.rs
- pallets/pallet-asset-switch/src/tests/set_switch_pair.rs
- pallets/pallet-asset-switch/src/tests/switch.rs
- pallets/pallet-asset-switch/src/tests/update_remote_fee.rs
- pallets/pallet-asset-switch/src/xcm/trade.rs
- pallets/pallet-asset-switch/src/xcm/transact.rs
- runtimes/common/src/xcm_config.rs
> fix: xcm swap pallet 

- chainspecs/spiritnet/spiritnet.json
> chore: Add stake.plus bootnodes

- nodes/parachain/src/chain_spec/rilt/new.rs
Update RILT for new chain spec generation
> fix: rilt chain spec

- .github/workflows/check-code.yml
Not sure how using all features would work and not using them would not, but if we always build the WASM of all required runtimes then all tests pass.
> fix: cargo tests

- Cargo.lock
- Dockerfile
- nodes/parachain/src/chain_spec/utils.rs
- runtimes/kestrel/Cargo.toml
- runtimes/kestrel/src/lib.rs
Fixes https://github.com/KILTprotocol/ticket/issues/3596 and fixes https://github.com/KILTprotocol/ticket/issues/3598.
> fix: node-side panics after refactoring

- .gitlab-ci.yml
Fixes https://github.com/KILTprotocol/ticket/issues/3603.
> ci: try-runtime WASMs in release pipeline

- .github/workflows/check-code.yml
> fix: benchmark test CI

- pallets/pallet-asset-switch/README.md
Code paths changed which broke documentation that replied on this file.
> Update switch pallet read me to change file paths

- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/types.rs
Introduces types and storage maps.
> feat: types for storage

- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/types.rs
Combines some changes that result from discussions on the feature branches but are more general than the individual features.
> refactor: bonded coins wireframe adjustments

- pallets/pallet-bonded-coins/src/curves/mod.rs
- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/types.rs
Fixes some smaller bugs, linter warnings, and concerns voiced in reviews. 
> fix: lints and nitpicks

- pallets/pallet-bonded-coins/src/curves/mod.rs
- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/tests/curves/lmsr.rs
- pallets/pallet-bonded-coins/src/tests/curves/polynomial.rs
- pallets/pallet-bonded-coins/src/tests/curves/square_root.rs
- pallets/pallet-bonded-coins/src/traits.rs
Found a merge artefact that needs fixing and fixed some lints while at it.
> fix: more lints

- pallets/pallet-bonded-coins/src/lib.rs
Little bug in the total sum calculation
> fix: total supply

- pallets/pallet-bonded-coins/src/traits.rs
We need to make the traits generic against the pallet-asset instance
> fix: change traits

- pallets/pallet-bonded-coins/src/tests/transactions/mod.rs
- pallets/pallet-bonded-coins/src/tests/transactions/refund_account.rs
- pallets/pallet-bonded-coins/src/tests/transactions/start_refund.rs
> test: refund

- pallets/pallet-bonded-coins/README.md
- pallets/pallet-bonded-coins/src/benchmarking.rs
- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/mock.rs
- pallets/pallet-bonded-coins/src/tests/transactions/create_pool.rs
- pallets/pallet-bonded-coins/src/traits.rs
Adresses the discussion at https://github.com/KILTprotocol/kilt-node/pull/764#discussion_r1862257153
> refactor: get next asset id via hook

- pallets/pallet-bonded-coins/src/mock.rs
> fix: mocks

- runtimes/common/src/constants.rs
- runtimes/peregrine/src/kilt/mod.rs
> feat: increase string limit 

- .maintain/build-image.sh
- pallets/pallet-bonded-coins/src/lib.rs
- runtime-api/bonded-coins/src/pool_details.rs
- runtimes/peregrine/src/runtime_apis.rs
Currently, the runtime call does not return the pool ID.
> feat: add pool id to runtime api

- .github/workflows/check-docs-pr.yml
> ci: docs pr checker

- .gitignore
- integration-tests/chopsticks/README.md
- integration-tests/chopsticks/package.json
- integration-tests/chopsticks/src/cli.ts
- integration-tests/chopsticks/src/command/index.ts
- integration-tests/chopsticks/src/command/network.ts
- integration-tests/chopsticks/src/command/scheduleTx.ts
- integration-tests/chopsticks/src/command/stateTransition.ts
- integration-tests/chopsticks/src/network/index.ts
- integration-tests/chopsticks/src/network/utils.ts
- integration-tests/chopsticks/src/tests/switchPallet/switchConfig/otherReserveLocation/index.test.ts
- integration-tests/chopsticks/src/tests/switchPallet/trappedAssets/index.test.ts
- integration-tests/chopsticks/src/tests/utils.ts
- integration-tests/chopsticks/yarn.lock
Adds some basic chopsticks functionality + a CLI.
> chore: chopsticks utils

- chainspecs/spiritnet/spiritnet.json
Rename bootnodes domain and id
<details>
```
```
</details>
<details>
<summary>Spiritnet Diff</summary>
```
```
</details>
> chore: fix bootnode id
