KILTprotocol/kilt-node

- runtime/Cargo.lock
- runtime/src/attestation/mod.rs
- runtime/src/attestation/tests.rs
- runtime/src/ctype/mod.rs
- runtime/src/ctype/tests.rs
- runtime/src/delegation/mod.rs
- runtime/src/delegation/tests.rs
- runtime/src/did/mod.rs
- runtime/src/did/tests.rs
- runtime/src/error/mod.rs
- runtime/wasm/Cargo.lock
Fixes https://github.com/KILTprotocol/ticket/issues/304
Fixes https://github.com/KILTprotocol/ticket/issues/222
The return value for queries where the query does not match anything is defined as follows in substrate:
a. If the return type is an Option or wrapped in an option, return `Option<null>`
b. If the return type is not an Option, return the fallback value, which defaults to a Hex zero value of the appropriate length (`0x00000...`)
So far, we were relying on fallback values, but these make results hard to interpret in the SDK ([see this issue, for example](https://github.com/KILTprotocol/sdk-js/pull/218)). 
This set of changes wraps return values in an Option where query methods were relying on fallback values. 
As an example, `ctype.ctypes()` will now return an `Option<AccountID>`. …
> feat: return Option from queries

- src/chain_spec.rs
fixes https://github.com/KILTprotocol/ticket/issues/308
With this change, identities Alice and Bob are token holders on any fresh dev chain. With this, we can test things that require more than one token holding identity without relying on transferring tokens from the faucet.
This, for example, makes SDK testing easier and faster and more reliable.
build and purge, then run the following test in the SDK:
```
import { Identity } from "."
import { getBalance } from "./balance/Balance.chain"
import BN = require("bn.js")
import getCached from "./blockchainApiConnection"
test('Bob', async() => {
const bobby = Identity.buildFromURI('//Bob')
const balance = await getBalance(bobby.address)
expect(balance.gt(new BN(0))).toBeTruthy()
})
test('Alice', async() => {
const alice = …
```
> feat: add alice & bob to endowed identities on dev

- README.md
The path of the freshly built mashnet node binary was wrong in the README, which would confuse anyone trying to use it (incl me when I started in December). Fixed this.
> docs: updated node binary paths in README

- .dockerignore
- Dockerfile
- docker-compose.yml
Speeds up docker builds by using a rust-nightly image, thus skipping the rust installation bit.
Also compiles dependencies in separate steps to avoid cache invalidation by source file changes.
A `docker-compose.yml` is included to quickly spin up a dev node on port `9944` with a single `docker-compose up dev-node`. You can also run sdk integration tests against your local code with `docker-compose run sdk yarn test:integration` !
build and run the image with `docker-compose build` and use it. Run integration tests against it with `docker-compose run sdk yarn test:integration`.
> feature: faster docker image creation

- .github/workflows/aws-dev.yml
On pushes to develop, the docker image built for EWS and deployed to the devnet will also be pushed to the mashnet-node repository on docker hub under a dedicated tag (currently set to `develop`)
the latest commit 1554634 has triggered a successful test run pushing to docker hub ([here](https://github.com/KILTprotocol/mashnet-node/actions/runs/131928883)). You can also pull the image with `kiltprotocol/mashnet-node:develop` and test it.
> publishing dev images on dockerhub

- .dockerignore
- Dockerfile
To avoid cache invalidation whenever parity publish a new version of the image we use as a base image for the builder, I pinned this image to a specific digest.
> ci: pinned base image version to avoid cache invalidation

- src/chain_spec.rs
Updating the unit denomination and name
Changing the properties doesn't affect the genesis block.
Spun up two nodes, one with the changes and the other without. They were able to connect without conflicts.
> feat: unit denomination

- scripts/init.sh
Adds specific nightly version, as newer might cause issues building. This is the [officially advised](https://substrate.dev/docs/en/knowledgebase/getting-started/#rust-nightly-toolchain) version: nightly-2020-10-06
Use script file.
read  ~/.rustup/settings.toml
mashnet-node path should have specific nightly set as override
> feat: specifiy specific nightly channel

- chainspec-devnet-nonraw.json
- chainspec-devnet.json
- chainspec.json
Adds dudleys changes to the chain unit properties to the actual spec files.
> feat: added unit denomination to chain spec properties

- pallets/did/src/default_weights.rs
- pallets/did/src/lib.rs
- pallets/did/src/mock.rs
- pallets/did/src/tests.rs
Add support to delete all the information associated with a DID from the chain.
Run `cargo test`.
1. Follow the steps in https://github.com/KILTprotocol/mashnet-node/pull/127 to create a new test identity and test DID
2. Open the UI to invoke a `submitDidDeleteOperation` extrinsic
3. `did: DIDIdentifier` -> select the test account created
4. `tx_counter: U64` -> insert `1`
5. `signature: DidSignature` -> select `Ed25519` and value `0x1901e750f8fb18486858ac59136e6448974afb1b3da4adb184e7453aa2fe4352f210a1e57a12c536d88ccbd0b0569c9cbf99fb6d4623e1071c0fb98087d6dc07` (this is the signature over the encoded delete operation)
Now, if you try to re-execute the same operation, the extrinsic will fail with a `did.DidNotPresent` error.
> feat: add support for DID removal

- Cargo.lock
- nodes/parachain/Cargo.toml
- nodes/parachain/src/cli.rs
- nodes/parachain/src/command.rs
- nodes/parachain/src/service.rs
* adds benchmarking command to parachain runtime
```bash
cd nodes/parachain
cargo run --release --features runtime-benchmarks -- benchmark --execution=wasm --wasm-execution=Compiled --heap-pages=4096 --extrinsic=\* --pallet=kilt_launch --steps=10 --repeat=4 --output ../../pallets/kilt-launch/src/default_weights.rs --template ../../.maintain/weight-template.hbs
```
(https://github.com/KILTprotocol/type-definitions/pulls)
> feat: add benchmarking to parachain runtime

- pallets/delegation/src/lib.rs
- pallets/delegation/src/tests.rs
Revoking a delegation root without any children didn't work since we misused the returned value of `revoke_children`. `revoke_children` doesn't return the remaining revocations, but the number of revoked children.
No Change
> fix: couldn't revoke empty delegation root

- pallets/kilt-launch/src/lib.rs
- pallets/kilt-launch/src/mock.rs
- pallets/kilt-launch/src/tests.rs
>  When I migrate an account with a locked amount that unlocks at a block that is already in the past (block the amount is unlocked: 250 and the current block is 500), the amount is not unlocked.
> fix: don't transfer expired locks

- primitives/src/constants.rs
- runtimes/parachain/src/lib.rs
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/src/lib.rs
> feat: set existential deposit to 10 milliKILT

- runtimes/parachain/src/lib.rs
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/src/lib.rs
Sorry @wischli you need to review again! 😂 Should have been 0.1 KILT = 100 milliKILT and not  0.01
> feat: set existential deposit to 0.1 KILT

- runtimes/parachain/src/lib.rs
- runtimes/spiritnet/src/lib.rs
() returns always none
ConvertInto returns Some(accountId)
> fix: session set key

- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/src/lib.rs
Sets the existential deposit to 0.01 KILT
constants -> balance -> existentialDeposit
> feat: set existential deposit to 0.01 KILT

- pallets/parachain-staking/src/lib.rs
* Replaces staking migrations based on the latest version with chained migrations from the earliest to the latest version
```
RUST_LOG=info cargo run -p kilt-parachain --features try-runtime -- try-runtime --chain=spiritnet-dev --execution wasm --wasm-execution compiled on-runtime-upgrade live wss://westend.kilt.io
```
```
cargo run --release -p kilt-parachain --features try-runtime build-spec --chain wilt-new --disable-default-bootnode --raw > wilt-try-runtime.json
RUST_LOG=info cargo run -p kilt-parachain --features try-runtime -- try-runtime --chain=wilt-try-runtime.json --execution wasm --wasm-execution compiled on-runtime-upgrade live wss://westend.kilt.io
```
```
RUST_LOG=info cargo run -p kilt-parachain --features try-runtime -- try-runtime --execution wasm --wasm-execution …
```
> fix: enable chained staking migrations

- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/src/lib.rs
Bump runtime version to allow for runtime upgrade on peregrine staging.
> chore: bump runtime version

- pallets/parachain-staking/src/benchmarking.rs
- pallets/parachain-staking/src/lib.rs
- pallets/parachain-staking/src/set.rs
- pallets/parachain-staking/src/types.rs
in preparation of KILTprotocol/mashnet-node/pull/244
* don't store the selected candidates in a separate list
* `select_top_candidates` -> `update_total_stake`
* ensure that the set is always sorted (no mutation without resorting)
storage migration will be handled in KILTprotocol/mashnet-node/pull/244
> refactor: staking

- pallets/parachain-staking/src/benchmarking.rs
- pallets/parachain-staking/src/lib.rs
- pallets/parachain-staking/src/migrations/v4.rs
- pallets/parachain-staking/src/tests.rs
- pallets/parachain-staking/src/types.rs
Refactoring part of KILTprotocol/mashnet-node/pull/244
> refactor(staking): Collator -> candidate

- pallets/parachain-staking/src/benchmarking.rs
- pallets/parachain-staking/src/default_weights.rs
- pallets/parachain-staking/src/lib.rs
- pallets/parachain-staking/src/migrations.rs
- pallets/parachain-staking/src/migrations/v4.rs
- pallets/parachain-staking/src/mock.rs
- pallets/parachain-staking/src/set.rs
- pallets/parachain-staking/src/tests.rs
- pallets/parachain-staking/src/types.rs
- runtimes/peregrine/src/lib.rs
- runtimes/peregrine/src/weights/parachain_staking.rs
- runtimes/spiritnet/src/lib.rs
- runtimes/spiritnet/src/weights/parachain_staking.rs
* remove 'cache' for selected candidates, calculate on the fly
* replace {increase, decrease}_max_candidate_stake with simple set_max_candidate_stake
* don't adjust existing collator stake. If root wants to adjust the stake, they need to adjust the existing stake manually with root calls. 
This PR introduces new custom JS-types which are required for compatibility with [our SDK](https://github.com/KILTprotocol/sdk-js) and the [Polkadot Apps](https://polkadot.js.org/apps/#/extrinsics). Please use the following types to test the code with the Polkadot Apps:
<details>
<summary>JS-Types</summary>
```js
{
Candidate: {
id: "AccountId",
stake: "Balance",
delegators: "Vec<Stake>",
total: "Balance",
state: "CollatorStatus",
},
CandidateOf: "Candidate",
Collator: undefined,
CollatorOf: undefined,
} …
```
> feat: unlimited candidates

- nodes/parachain/res/spiritnet.json
Adds dedicated hetzner nodes as bootnodes.
This PR introduces new custom JS-types which are required for compatibility with [our SDK](https://github.com/KILTprotocol/sdk-js) and the [Polkadot Apps](https://polkadot.js.org/apps/#/extrinsics). Please use the following types to test the code with the Polkadot Apps:
<details>
<summary>JS-Types</summary>
```json
{}
```
</details>
> Adds dedicated bootnodes

- pallets/parachain-staking/src/lib.rs
- pallets/parachain-staking/src/migrations.rs
- pallets/parachain-staking/src/migrations/v6.rs
- pallets/parachain-staking/src/tests.rs
- pallets/parachain-staking/src/types.rs
* Fixes unwanted removal of delegator state if `join_delegators` or `delegate_another_candidate` extrinsics failed due to failure in `increase_lock` (either insufficient balance or full unstaking list) by delaying removal until tx cannot fail anymore
* Adds balance checks to head of corresponding delegation extrinsics
* Adds corresponding unit test
> fix: unwanted delegator state removal when tx fails

- pallets/delegation/src/migrations.rs
- pallets/did/src/migrations.rs
- pallets/parachain-staking/src/migrations.rs
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/src/lib.rs
* Adds missing migrations for collective and membership pallets which moves the pallets storage from an old prefix to a new one
* Includes fixes for StorageVersions of delegations and parachain-staking (cherry-picked from #285)
* Requires clearing storage items for new prefix and setting storage version to non-default beforehand (see Requirements)
Tested with `try-runtime` for
1. In your `.cargo/.../frame/vesting/src/migrations.rs` remove this pre-migration check:
```
// assert!(StorageVersion::<T>::get() == Releases::V0, "Storage version too high.");
```
2a. For WILT run
```
cargo run --release -p kilt-parachain --features try-runtime -- try-runtime --chain=spiritnet-dev --execution=native  on-runtime-upgrade live --uri=wss://westend.kilt.io/
```
2b. For Peregrine run
```
cargo run …
```
> fix: missing migrations for collective and membership pallets

- Cargo.lock
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- pallets/attestation/Cargo.toml
- pallets/crowdloan/Cargo.toml
- pallets/ctype/Cargo.toml
- pallets/delegation/Cargo.toml
- pallets/did/Cargo.toml
- pallets/kilt-launch/Cargo.toml
- pallets/pallet-did-lookup/Cargo.toml
- pallets/pallet-inflation/Cargo.toml
- pallets/parachain-staking/Cargo.toml
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/Cargo.toml
- runtimes/standalone/src/lib.rs
- support/Cargo.toml
* Bumps pallet versions to 1.4.0 from 1.3.0
* Bumps spec versions to 10400 from 10310
> Version 1.4.0

- Cargo.lock
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- pallets/attestation/Cargo.toml
- pallets/ctype/Cargo.toml
- pallets/delegation/Cargo.toml
- pallets/did/Cargo.toml
- pallets/kilt-launch/Cargo.toml
- pallets/pallet-did-lookup/Cargo.toml
- pallets/pallet-inflation/Cargo.toml
- pallets/parachain-staking/Cargo.toml
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/Cargo.toml
- runtimes/standalone/src/lib.rs
- support/Cargo.toml
* Bumps pallet versions to 1.4.1 from 1.4.0
* Bumps spec versions to 10410 from 10400
> version 1.4.1

- pallets/attestation/src/attestations.rs
- pallets/attestation/src/lib.rs
- pallets/ctype/src/lib.rs
- pallets/delegation/src/delegation_hierarchy.rs
- pallets/delegation/src/lib.rs
- pallets/delegation/src/migrations.rs
- pallets/did/src/did_details.rs
- pallets/did/src/lib.rs
- pallets/did/src/origin.rs
- pallets/did/src/service_endpoints.rs
- pallets/kilt-launch/src/lib.rs
- pallets/pallet-did-lookup/src/connection_record.rs
- pallets/pallet-did-lookup/src/lib.rs
- pallets/pallet-inflation/src/lib.rs
- pallets/pallet-web3-names/src/lib.rs
- pallets/pallet-web3-names/src/web3_name.rs
- pallets/parachain-staking/src/inflation.rs
- pallets/parachain-staking/src/lib.rs
- pallets/parachain-staking/src/set.rs
- pallets/parachain-staking/src/types.rs
- support/src/deposit.rs
- support/src/mock.rs
* Implements/derives `MaxEncodedLen` for all required pallets' structs such that each pallet's storage size is bound
* Removes `#[pallet::without_storage_info]` from all pallets 
The usage of the `#[codec(mel_bound(Generic: TraitBound))]` feature is often required because the compiler is not smart enough to derive `MaxEncodedLen`
* `mel_bound()` means no bound is added at all. We can use this if encapsulated associated types are already bound by the `MaxEncodedLen` trait
* If we provide attributes, we tell the macro which trait bounds to add. This was only required in the staking pallet where we used unbound generics for the AccountId and balance. In 8a5d744a54343062f1d74d778e43a4c7410a7e3f you can see how many bounds could be removed eventually. Shawn did it similarly in [this Substrate …
> feat: bound pallets in runtime storage size

- .maintain/reset-spec/peregrine_relay.py
- dev-specs/kilt-parachain/peregrine-relay.json
Adds two more peregrine relaychain bootnodes
> fix: Adds two more bootnodes for peregrine relaychain

- .gitlab-ci.yml
- .maintain/ci.Dockerfile
skipping one step should speed up the build
[The Dockerfile can be found in our deployment repository](https://github.com/KILTprotocol/kubernetes/blob/master/container/ci.Dockerfile)
> ci: use custom ci image

- Cargo.lock
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- pallets/attestation/Cargo.toml
- pallets/ctype/Cargo.toml
- pallets/delegation/Cargo.toml
- pallets/did/Cargo.toml
- pallets/kilt-launch/Cargo.toml
- pallets/pallet-did-lookup/Cargo.toml
- pallets/pallet-inflation/Cargo.toml
- pallets/pallet-web3-names/Cargo.toml
- pallets/parachain-staking/Cargo.toml
- runtimes/common/Cargo.toml
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/Cargo.toml
- runtimes/standalone/src/lib.rs
- support/Cargo.toml
Supersedes https://github.com/KILTprotocol/mashnet-node/pull/346 (branch renaming).
> chore: v1.6.1

- Cargo.lock
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- nodes/standalone/build.rs
- nodes/standalone/src/chain_spec.rs
- pallets/attestation/Cargo.toml
- pallets/ctype/Cargo.toml
- pallets/delegation/Cargo.toml
- pallets/did/Cargo.toml
- pallets/did/src/did_details.rs
- pallets/did/src/service_endpoints.rs
- pallets/kilt-launch/Cargo.toml
- pallets/pallet-did-lookup/Cargo.toml
- pallets/pallet-inflation/Cargo.toml
- pallets/pallet-web3-names/Cargo.toml
- pallets/pallet-web3-names/src/mock.rs
- pallets/pallet-web3-names/src/web3_name.rs
- pallets/parachain-staking/Cargo.toml
- pallets/parachain-staking/src/set.rs
- runtimes/common/Cargo.toml
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/Cargo.toml
- runtimes/standalone/src/lib.rs
- support/Cargo.toml
* Use RuntimeDebug to avoid manual implementation
* update build script for standalone
* upgrade dependencies
* don't disable default features for dev-dependencies
* fix accounts for sporran chain
> chore: upgrade and clean up

- dev-specs/kilt-parachain/rococo-v2-relay.json
We should have downloaded via wget with init container yet for now Check line 21 : https://paritytech.github.io/chainspecs/rococo/relaychain/chainspec.json
> fix: rococo protocol id

- .gitlab-ci.yml
- Cargo.lock
- Dockerfile
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- pallets/attestation/Cargo.toml
- pallets/ctype/Cargo.toml
- pallets/delegation/Cargo.toml
- pallets/did/Cargo.toml
- pallets/pallet-did-lookup/Cargo.toml
- pallets/pallet-inflation/Cargo.toml
- pallets/pallet-web3-names/Cargo.toml
- pallets/parachain-staking/Cargo.toml
- runtimes/common/Cargo.toml
- runtimes/peregrine/Cargo.toml
- runtimes/spiritnet/Cargo.toml
- runtimes/standalone/Cargo.toml
- support/Cargo.toml
* Upgrades to most recent [Polkadot version 0.9.24](https://github.com/paritytech/polkadot/releases/tag/v0.9.24)
* Changes are entirely client-based
* No code changes required
> feat: upgrade to Polkadot v0.9.24

- Cargo.lock
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- pallets/attestation/Cargo.toml
- pallets/ctype/Cargo.toml
- pallets/delegation/Cargo.toml
- pallets/did/Cargo.toml
- pallets/pallet-did-lookup/Cargo.toml
- pallets/pallet-inflation/Cargo.toml
- pallets/pallet-web3-names/Cargo.toml
- pallets/parachain-staking/Cargo.toml
- runtimes/common/Cargo.toml
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/Cargo.toml
- runtimes/standalone/src/lib.rs
- support/Cargo.toml
> version 1.7.1

- Cargo.lock
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- pallets/parachain-staking/Cargo.toml
- rpc/did/Cargo.toml
- rpc/did/runtime-api/Cargo.toml
- runtimes/common/Cargo.toml
- runtimes/peregrine/Cargo.toml
- runtimes/spiritnet/Cargo.toml
- runtimes/standalone/Cargo.toml
- scripts/all.fish
Remove unused dependencies using `cargo udeps`. It also updates the `all.fish` script to check for `--all-targets` and remove the actual tests running, since we do not need those.
> chore: remove unused dependencies

- Cargo.lock
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- pallets/attestation/Cargo.toml
- pallets/ctype/Cargo.toml
- pallets/delegation/Cargo.toml
- pallets/did/Cargo.toml
- pallets/pallet-did-lookup/Cargo.toml
- pallets/pallet-inflation/Cargo.toml
- pallets/pallet-web3-names/Cargo.toml
- pallets/parachain-staking/Cargo.toml
- rpc/did/Cargo.toml
- rpc/did/runtime-api/Cargo.toml
- runtimes/common/Cargo.toml
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/Cargo.toml
- runtimes/standalone/src/lib.rs
- support/Cargo.toml
- support/src/mock.rs
* Upgrades to [latest Polkadot v0.9.26](https://github.com/paritytech/polkadot/releases/tag/v0.9.26)
* No database or runtime migrations required
Noteworthy mentions
* [S] ✅ audited https://github.com/paritytech/substrate/pull/11618 Low - Add event to pallet transaction payment
* [P] ✅ trivial https://github.com/paritytech/polkadot/pull/5597 ❗️ Medium - Allow relay chain council to send xcms
* [S] ✅ audited https://github.com/paritytech/substrate/pull/11666 ❗️ Medium - Democracy.fast_track not allowed with zero voting period
* [S] ✅ trivial https://github.com/paritytech/substrate/pull/11694 ❗️ Medium - Pump the gossip engine while waiting for the beefy runtime pallet (memory leak fix)
> feat: upgrade to Polkadot v0.9.26

- pallets/parachain-staking/src/benchmarking.rs
- pallets/parachain-staking/src/lib.rs
- pallets/parachain-staking/src/mock.rs
- pallets/parachain-staking/src/tests.rs
- pallets/parachain-staking/src/types.rs
- runtimes/common/src/constants.rs
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/src/lib.rs
This PR removes unused code from the staking pallet, mainly the unusable `delegate_another_candidate` extrinsic, `revoke_delegation` extrinsic and two useless staking parameters.
While working on #384 I just stumbled the problem in the current redesign introduced by allowing for more than one delegation per delegator (which we do in the unit test environment). As discussed, we don't seem to plan supporting multiple delegations from the same account in the future.
- `delegate_another_candidate` extrinsic
- `revoke_delegation` extrinsic (not needed because of `leave_delegators`)
- Comments about the `weight` of functions in the Staking Pallet
- `Delegator` struct (it's just `Stake`)
- `ReplacedDelegator` struct, not needed anymore
- `NomStakeBelowMin` error (redundant because of …
> feat: remove multiple delegations

- Cargo.lock
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- pallets/attestation/Cargo.toml
- pallets/ctype/Cargo.toml
- pallets/delegation/Cargo.toml
- pallets/did/Cargo.toml
- pallets/pallet-did-lookup/Cargo.toml
- pallets/pallet-inflation/Cargo.toml
- pallets/pallet-web3-names/Cargo.toml
- pallets/parachain-staking/Cargo.toml
- pallets/relay-migration/Cargo.toml
- runtimes/clone/Cargo.toml
- runtimes/clone/src/lib.rs
- runtimes/common/Cargo.toml
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/Cargo.toml
- runtimes/standalone/src/lib.rs
- support/Cargo.toml
Supersedes #400
* Bumps versions to v1.7.2 or 10720 respectively
> feat: version 1.7.2

- pallets/did/src/benchmarking.rs
- pallets/parachain-staking/src/benchmarking.rs
Moves all allocations our of the benchmarking clause. The allocations would otherwise influence the benchmarking results.
> fix: clone and allocation while benchmarking

- .gitlab-ci.yml
- .maintain/docker-auth-config.sh
Gitlab authenticates with the private registry using `DOCKER_AUTH_CONFIG` that expires every 12 hours hence needs to be rotated ahead of wasm building stage.
> ci: Rotate DOCKER_AUTH_CONFIG

- .gitlab-ci.yml
- .maintain/ci.Dockerfile
Upgrades the kilt ci to latest stable version , adds jq and push to  [kiltprotocol repository](https://hub.docker.com/r/kiltprotocol/kilt-ci/tags)
> ci: upgrade and add jq

- pallets/pallet-did-lookup/src/linkable_account.rs
After spending a considerable amount of time for making the DID RPC using the new linkable accounts work, I stumbled across the following conversation: https://github.com/polkadot-js/api/issues/3367.
TL;DR: the polkadot api library expects any serde stuff to follow a `camelCase` capitalization. This PR fixes that for the `LinkableAccountId` type. I tested with the latest type definitions, and it now seems to be working fine.
> fix: serde encoding for LinkableAccountId

- Cargo.lock
- crates/assets/Cargo.toml
- nodes/common/Cargo.toml
- nodes/parachain/Cargo.toml
- nodes/standalone/Cargo.toml
- pallets/attestation/Cargo.toml
- pallets/ctype/Cargo.toml
- pallets/delegation/Cargo.toml
- pallets/did/Cargo.toml
- pallets/pallet-did-lookup/Cargo.toml
- pallets/pallet-inflation/Cargo.toml
- pallets/pallet-web3-names/Cargo.toml
- pallets/parachain-staking/Cargo.toml
- pallets/public-credentials/Cargo.toml
- rpc/did/runtime-api/Cargo.toml
- rpc/public-credentials/Cargo.toml
- rpc/public-credentials/runtime-api/Cargo.toml
- runtimes/clone/Cargo.toml
- runtimes/clone/src/lib.rs
- runtimes/common/Cargo.toml
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/Cargo.toml
- runtimes/standalone/src/lib.rs
- support/Cargo.toml
Right now, it is very very **very** hard for the SDK to try to make sense of how to encode and decode stuff to and from the blockchain. This is due to the fact that we have same runtime, same `spec_version`, same `transaction_version`, and same `everything_else` both in our `master` branch and in our `develop` branch.
This normally would not be an issue, but right now we have a big breaking change between the two, where `master` only deals with `AccountId32` stuff, while `develop` deals with `LinkableAccountId`.
Types in the SDK can be cleverly defined as starting from a given spec_version number, hence I am proposing the following:
_always make sure that the `spec_version` number on `develop` is higher than the `spec_version` number on `master` and any released binaries._
This also …
> chore: bump development spec_version to 1.8.0

- pallets/delegation/src/lib.rs
Move the Pallet impl block into the pallet module like we do it for all other pallets as well.
> refactor(delegation): move impl Pallet into pallet mod

- Cargo.lock
- nodes/standalone/Cargo.toml
- nodes/standalone/src/chain_spec.rs
> fix: yorlin keys

- Cargo.lock
- Cargo.toml
> chore: make clear that it's still under development

- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/src/lib.rs
Brings the two runtimes back to sync. The diff between the peregrine and spiritnet runtime is now minimal again.
Also one comment was outdated and the public credentials are not part of the benchmarks for spiritnet.
> fix: add public credentials to benchmark

- .gitlab-ci.yml
Fixes https://github.com/KILTprotocol/ticket/issues/2409.
> fix: set right env variables for srtool and subwasm

- crates/assets/src/asset.rs
- crates/assets/src/chain.rs
- runtimes/common/src/constants.rs
Fixes https://github.com/KILTprotocol/ticket/issues/2458.
- CAIP-19 asset reference max length was increased to 128: https://github.com/ChainAgnostic/CAIPs/pull/179
- CAIP-2 chain reference now supports underscores: https://github.com/ChainAgnostic/CAIPs/pull/180
- CAIP-19 asset reference and asset identifier now support `.` and `%` symbols: https://github.com/ChainAgnostic/CAIPs/pull/160
Not a breaking change since it just relaxes some requirements.
> chore: update CAIP limits and allowed charset

- .github/workflows/polkadot-release-list.yml
Fixes https://github.com/KILTprotocol/ticket/issues/2403.
I was playing around with `subalfred` and found out this nice feature, which we might want to integrate into our update flow. The action is configured to be run manually by providing the versions we are updating from and to.
~There is one thing that would break if we keep changing the weekly board project name to include the sprint goal, I think we could start tracking that separately.~ -> replaced `project-name` with `project-number`, thanks @ggera 
What do you guys think? Would it make sense?
> chore: add manual trigger for Polkadot releases dependencies

- .github/workflows/polkadot-version-upgrade-ticket.yml
Polkadot release branch naming has a different convention since it starts with `release`. I thought it was simply not supported by subalfred, but I was simply too tired to notice that 😄
Just launched a test run from this branch: https://github.com/KILTprotocol/kilt-node/actions/runs/4280433199/jobs/7452196855, which created the new ticket https://github.com/KILTprotocol/kilt-node/issues/481.
> chore: add polkadot output to Subalfred

- Cargo.lock
- Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/src/lib.rs
- runtimes/standalone/src/lib.rs
increase the development version.
Future work on the develop branch will be part of 1.11.0. We therefore set the version to 1.11.0-dev.
In this PR I also removed an unused dependency (`cumulus-pallet-solo-to-para`) and reordered the dependencies in the Cargo.toml.
> chore: Bump to 1.11.0-dev

- .gitlab-ci.yml
* remove 1h timeouts since that is the default
* increase build timeout to 2h since LTO takes more time?
> ci: increase build timeout

- Cargo.lock
- dip-template/runtimes/dip-receiver/Cargo.toml
- dip-template/runtimes/dip-receiver/src/dip.rs
- dip-template/runtimes/dip-receiver/src/lib.rs
- pallets/pallet-dip-receiver/src/lib.rs
- pallets/pallet-dip-receiver/src/origin.rs
- pallets/pallet-dip-receiver/src/traits.rs
- runtimes/common/src/dip/receiver.rs
Fixes https://github.com/KILTprotocol/ticket/issues/2587.
This PR adds a new trait `DipCallOriginFilter` that exposes a `fn check_proof(call: Call, proof: Self::Proof) -> Result<Self::Success, Self::Error>` function, called by the runtime to verify if a call can be dispatched with the provided proof or not.
> feat: add DID key verification relationship logic

- .gitlab-ci.yml
- runtimes/common/src/migrations.rs
Fixes https://github.com/KILTprotocol/ticket/issues/2637.
I wanted to also remove the `test-features` step, but we still do something weird inside the DID pallet, so I would remove that only when we have a proper mechanism in place to distinguish between tests and tests + benchmarks flag.
I also fixed a small Clippy warning for the randomness pallet removal migration 😄
> chore: update gitlab cargo test steps

- dip-template/runtimes/dip-provider/src/dip.rs
- dip-template/runtimes/xcm-tests/src/tests.rs
- pallets/pallet-dip-provider/src/lib.rs
Identity information should be entirely under the control of the DID subject. Until now, it was not the case as anyone could have called the `commit_identity` extrinsic for any DID subject.
This PR changes the origin check for the `commit_identity` extrinsic of provider pallet from `EnsureSigned` to a configurable origin check.
The XCM integration tests have also been updated to use the `EitherOfDiverse<EnsureRoot<AccountId>, EnsureDidOrigin<DidIdentifier, AccountId>>;` implementation.
Now, except for cases where democracy decides to do this operation, the DID subject has to agree to it by signing the operation, which will then be dispatched via the `submit_did_call` extrinsic of the DID pallet.
The feature that any account can pay for the fees still applies, as that is the same also for …
> feat: configurable origin check for 'commit_identity'

- pallets/did/src/mock_utils.rs
- pallets/did/src/service_endpoints.rs
- pallets/did/src/utils.rs
Fixes https://github.com/KILTprotocol/ticket/issues/2626.
Right now, we only check for `is_ascii()` for all elements of a DID service. The [DID core spec](https://www.w3.org/TR/did-core/#services) defines a service ID and a service endpoints as URIs by requiring the presence of a `#`, which makes an ID and a service endpoint without the leading `kilt:did:...` prefix a fragment by all means. This PR implements this requirement, by only allowing fragment-allowed characters as part of a service ID and endpoint, further restricting the set to not include percent-encoded characters, for the sake of ease of implementation, without deviating from the standard (which we now kinda do). This requirement can be relaxed in the future, if needed.
> feat: restrict charset of a DID service ID and endpoint

- runtimes/peregrine/Cargo.toml
- runtimes/spiritnet/Cargo.toml
Add `with-tracing` feature to the peregrine and spiritnet runtime.
This should never be used for production runtimes. But runtimes build with tracing support can be used to temporarily replace the on-chain code (`--wasm-runtime-overrides`).
> feat: add tracing support to peregrine&spiritnet

- runtimes/common/src/constants.rs
Increase the duration of Council and Technical Committee votes from 3 days to 7 days.
> feat: increase vote duration to 7d

- Cargo.lock
- Cargo.toml
- crates/kilt-dip-support/src/lib.rs
- crates/kilt-dip-support/src/state_proofs.rs
- crates/kilt-dip-support/src/traits.rs
- dip-template/nodes/dip-consumer/src/chain_spec.rs
- dip-template/pallets/pallet-postit/Cargo.toml
- dip-template/pallets/pallet-postit/src/lib.rs
- dip-template/pallets/pallet-postit/src/post.rs
- dip-template/pallets/pallet-postit/src/traits.rs
- dip-template/runtimes/dip-consumer/Cargo.toml
- dip-template/runtimes/dip-consumer/src/dip.rs
- dip-template/runtimes/dip-consumer/src/lib.rs
- dip-template/runtimes/dip-consumer/src/origin_adapter.rs
- dip-template/runtimes/dip-provider/src/lib.rs
Builds on the new state proofs by adding support for a relay chain to be a consumer with the new `ChildParachainDipStateProof` and `DipChildProviderStateProofVerifier` types. Some traits and types have also been renamed.
The new feature has been tested with a local Rococo 0.9.43 deployment, and can be reproduced by download and compiling our Polkadot fork at the [demo-sub0-23 tag](https://github.com/KILTprotocol/polkadot/tree/demo-sub0-23).
This PR also adds the `postit` pallet that was written for the Decoded demo, and uses that instead of the lookup pallet as an example pallet integrating DIP.
> feat: add support for relay chain

- pallets/parachain-staking/src/lib.rs
Not sure why the Clippy lint does not pop up every time, but the `assert_ok` macro is only used with the `std` feature, which resulted in a Clippy warning for me.
> fix: do not import top-level frame_support::assert_ok in pallet-staking

- pallets/did/src/lib.rs
the extrinsic was using the wrong DID for updating the deposit
> fix: use right did

- pallets/attestation/src/benchmarking.rs
- pallets/ctype/src/benchmarking.rs
- pallets/delegation/src/benchmarking.rs
- pallets/did/src/benchmarking.rs
- pallets/pallet-configuration/src/benchmarking.rs
- pallets/pallet-web3-names/src/benchmarking.rs
- pallets/public-credentials/src/benchmarking.rs
With the new syntax each benchmark case is tested individually. If one of them fails, you'll know exactly which one failed.
> refactor: update to the latest benchmark syntax

- .gitlab-ci.yml
This PR adds Wasm builds with the `try-runtime` feature enabled. This is in preparation for more automation in the release process.
> ci: add try-runtime builds

- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/src/lib.rs
- scripts/diff-runtimes.sh
This PR checks what's part of our runtime and what is not. We only didn't add the PolkadotXcm storage metadata. Everything else seems to be ok.
I still exclude the genesis config for `indices` and `transaction_payment` since we don't plan to customize them for any new chains. If we need them, we can still enable both.
<details>
```
!!! THE SUBWASM REDUCED DIFFER IS EXPERIMENTAL, DOUBLE CHECK THE RESULTS !!!
[≠] pallet 83: PolkadotXcm -> 12 change(s)
- storages changes:
[+] StorageDesc { name: "AssetTraps", modifier: "Default", default_value: [0, 0, 0, 0] }
[+] StorageDesc { name: "CurrentMigration", modifier: "Optional", default_value: [0] }
[+] StorageDesc { name: "LockedFungibles", modifier: "Optional", default_value: [0] }
[+] StorageDesc { name: …
```
> refactor: use explicit `exclude_parts`

- Cargo.lock
- crates/kilt-dip-support/Cargo.toml
- crates/kilt-dip-support/src/did.rs
- crates/kilt-dip-support/src/lib.rs
- crates/kilt-dip-support/src/merkle.rs
- crates/kilt-dip-support/src/state_proofs.rs
- crates/kilt-dip-support/src/utils.rs
- dip-template/runtimes/dip-consumer/src/dip.rs
- dip-template/runtimes/dip-provider/src/dip.rs
- dip-template/runtimes/dip-provider/src/lib.rs
- nodes/standalone/src/command.rs
- nodes/standalone/src/rpc.rs
- pallets/attestation/src/benchmarking.rs
- pallets/delegation/src/benchmarking.rs
- pallets/did/src/benchmarking.rs
- pallets/pallet-did-lookup/src/benchmarking.rs
- pallets/pallet-dip-consumer/src/lib.rs
- pallets/pallet-dip-provider/src/lib.rs
- pallets/pallet-migration/src/lib.rs
- pallets/pallet-migration/src/test.rs
- pallets/pallet-web3-names/src/benchmarking.rs
- pallets/parachain-staking/src/lib.rs
- runtimes/common/src/assets.rs
- runtimes/common/src/dip/did.rs
- runtimes/common/src/dip/merkle.rs
Fixes https://github.com/KILTprotocol/ticket/issues/2552, by both removing all occurrences of `.expect()` and `.unwrap()` and replacing them with `Internal` errors, and by introducing error enums. The logic is that for both the provider and the consumer, a generic error is bubbled up from the runtime, and because of the constraints imposed by Substrate, the error reason is encoded as a `u16`, where each "class" of error is namespaced with a 255 value increment. A snippet of this is shown below:
```rust
fn from(
value: DipSiblingProviderStateProofVerifierError<
ParachainHeadMerkleProofVerificationError,
IdentityCommitmentMerkleProofVerificationError,
DipProofVerificationError,
DidSignatureVerificationError
>,
) -> Self {
match value { …
```
> feat: add meaningful errors

- pallets/pallet-migration/src/lib.rs
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/src/lib.rs
There are two pallets with missing runtime migrations. The command try-runtime on-runtime-upgrade revealed them. This PR aims to fix the issue and set the correct storage version for the pallet.
> fix: include missing runtime migrations.

- pallets/did/src/origin.rs
- pallets/pallet-dip-consumer/src/lib.rs
- pallets/pallet-dip-provider/src/lib.rs
Ensuring the origin is a DID origin for the implementor of the provider pallet might not be enough. They need to check that the origin indeed matches the identifier being acted upon. Replacing `EnsureOrigin` with `EnsureOriginWithArg` gives access to that information.
Tests will ALL be implemented in a different PR 😄
> fix: origin checks for provider and consumer pallets

- .gitlab-ci.yml
- nodes/parachain/src/chain_spec.rs
- pallets/delegation/src/access_control.rs
- pallets/did/src/errors.rs
- pallets/did/src/lib.rs
- pallets/pallet-inflation/src/lib.rs
- pallets/parachain-staking/src/lib.rs
- pallets/public-credentials/src/lib.rs
- runtimes/common/src/assets.rs
- runtimes/common/src/lib.rs
- runtimes/common/src/migrations.rs
- runtimes/common/src/xcm_config.rs
Running `cargo doc` produces a bunch of warnings. Although we don't do much with them yet, it is nice that we make sure they are correct. Our test step already includes any snippets (we don't have any), but we don't check that the docs themselves are correct.
> chore: fix docs and add check step in CI

- Dockerfile
- dip-template/nodes/dip-consumer/Cargo.toml
- dip-template/nodes/dip-consumer/src/command.rs
- dip-template/nodes/dip-provider/Cargo.toml
- dip-template/nodes/dip-provider/src/command.rs
Zombienet uses the empty chainspec for a parachain, and that was not supported by the node templates. Also, the Dockerfile assumes the `kilt-parachain` is being run, but this is different now, and could also be different in the future, so the binary target should be parametrized: anyway, it is not necessary to compile the whole workspace if only a specific binary is required.
> feat: update templates and Dockerfile to support Zombienet

- pallets/attestation/src/authorized_by.rs
- pallets/attestation/src/benchmarking.rs
- pallets/attestation/src/lib.rs
- pallets/attestation/src/mock.rs
- pallets/attestation/src/tests/claim.rs
- pallets/attestation/src/tests/delete.rs
- pallets/attestation/src/tests/deposit.rs
- pallets/attestation/src/tests/revoke.rs
- pallets/delegation/src/lib.rs
- pallets/pallet-web3-names/src/lib.rs
Not sure about removing the `Attester` from the `AttestationRemoved` event. We could also consider to have an enum `Remover` with the variants `DepositOwner` and `AuthorizedAttester`. This could make sense since not only the original attester can remove an attestation but also any attester who is authorized via the `AuthorizationId`.
* moved the `deposit_event(Event::AttestationRemoved)` to the `remove_attestation` so that the event shall never be forgotten to be deposited.
* restructured Attestation event
* added authorized_by to revoked and removed, added ctype
* test attestation events
* removed unused `DepositReclaimed` events
* deposit `W3nReleased` event when governance bans an already used w3n
<details>
```
!!! THE SUBWASM REDUCED DIFFER IS …
```
> fix: check events

- .gitlab-ci.yml
Taken from https://github.com/rust-lang/cargo/issues/8424#issuecomment-1070988443. Otherwise CI would not highlight the issue.
> chore: convert errors into warning for `cargo doc`

- .gitlab-ci.yml
- .maintain/build-image.sh
- .maintain/push-image.sh
Partially fixes https://github.com/KILTprotocol/ticket/issues/3051. Needed for easier DIP-SDK integration tests. Binaries will have to be compiled and exported in a different PR.
> chore: add DIP templates Docker images

- dip-template/runtimes/dip-provider/src/dip.rs
- pallets/pallet-deposit-storage/src/deposit.rs
- pallets/pallet-dip-provider/src/lib.rs
- runtimes/peregrine/src/dip/deposit.rs
There was a circular call graph issue, where the deposit removal called the hook, which in turn tried to remove the deposit again. A new function on the `pallet-deposit-storage` is added which allows to delete a deposit without calling into the hook.
Benchmarks now run fine for both `pallet-deposit-storage` and `pallet-dip-provider` for both peregrine and DIP Provider template.
> fix: benchmarks

- runtimes/common/src/constants.rs
Fixes https://github.com/KILTprotocol/ticket/issues/3131.
The ticket mentions that 500 would be a good new limit for the inbound request we had. Reading elsewhere online, such as [here](https://stackoverflow.com/a/417184) it seems that 2000 characters is a good upper bound limit for URLs. Since every change would require a runtime upgrade, I would rather make the value future proof and set it to 2000 directly.
> feat: increase service URL size limit

- .gitlab-ci.yml
Fixes https://github.com/KILTprotocol/ticket/issues/3300.
Currently srtool does not really support features (https://github.com/chevdor/srtool-cli/issues/32), so we need a workaround until features are supported in srtool. Since this is what we do anyway now, I decided to go with using the same build infrastructure we use for tests.
> fix: try-runtime support in CI

- .gitlab-ci.yml
Fixes https://github.com/KILTprotocol/ticket/issues/3036.
> test: add test-try-runtime step to CI

- .gitlab-ci.yml
Output of a `try-runtime` execution with `--checks all`:
<details>
<summary>stdout</summary>
```
antonio@rust-2:~/Developer/kilt-node\ $ try-runtime --runtime target/debug/wbuild/spiritnet-runtime/spiritnet_runtime.compact.compressed.wasm on-runtime-upgrade --checks all live --uri wss://spiritnet.kilt.io:443
[2024-04-17T06:14:46Z INFO  remote-ext] replacing wss:// in uri with https://: "https://spiritnet.kilt.io:443" (ws is currently unstable for fetching remote storage, for more see https://github.com/paritytech/jsonrpsee/issues/1086)
[2024-04-17T06:14:46Z INFO  remote-ext] since no at is provided, setting it to latest finalized head, 0xef1391b41c362cd4175c25a5ea456a6e07200d6f82842d4b6ba79c648ac8fb38
[2024-04-17T06:14:46Z INFO  remote-ext] since no prefix is filtered, the data for all …
```
> chore: remove unnecessary try-runtime execution

- .gitlab-ci.yml
- integration-tests/chopsticks/package.json
- integration-tests/chopsticks/src/network/hydraDx.ts
- integration-tests/chopsticks/src/network/spiritnet.ts
- integration-tests/chopsticks/src/tests/index.ts
- integration-tests/chopsticks/src/tests/utils.ts
- integration-tests/chopsticks/src/tests/xcm/__snapshots__/limitedReserveTransferSpiritnetHydraDxV2.test.ts.snap
- integration-tests/chopsticks/src/tests/xcm/__snapshots__/limitedReserveTransferSpiritnetHydraDxV3.test.ts.snap
- integration-tests/chopsticks/src/tests/xcm/__snapshots__/limitedReseveTransferHydraDxSpiritnet.test.ts.snap
- integration-tests/chopsticks/src/tests/xcm/limitedReserveTransferSpiritnetHydraDxV2.test.ts
- integration-tests/chopsticks/src/tests/xcm/limitedReserveTransferSpiritnetHydraDxV3.test.ts
- integration-tests/chopsticks/src/tests/xcm/limitedReseveTransferHydraDxSpiritnet.test.ts
Fixes https://github.com/KILTprotocol/ticket/issues/3344.
Integration tests are outdated. Since KILT is now listed on HydraDX, any tokens sent to the Omnipool account is automatically transferred to the treasury, which makes the test cases fail. The integration test logic must be updated to test the following:
1. Send KILT tokens from a KILT account to **its own** sovereign account on HydraDX (implementation started in this PR for the V2 tests)
2. Send KILT tokens from HydraDX back to KILT (to implement in this PR)
> fix: outdated integration tests

- Cargo.toml
Fixes https://github.com/KILTprotocol/ticket/issues/3401.
The `lto = "fat"` settings results in much longer compilation times which are often not required for quick testing or prototyping where the default `debug` profile is too slow. This PR adds a new build profile called `release-unoptimized` which can be called with `cargo build --profile release-unoptimized` and puts build artifacts in the `target/release-unoptimized` folder. The default `--release` profile has one more flag `codegen-units = 1` which, according to the [documentation](https://doc.rust-lang.org/cargo/reference/profiles.html#codegen-units) reduces compilation times but increases performance of the compiled binary. Parity also [uses this](https://github.com/paritytech/polkadot-sdk/blob/313fe0f9a277f27a4228634f0fb15a1c3fa2 …
> chore: add new intermediate profile for unoptimized releases

- integration-tests/chopsticks/src/tests/xcm/__snapshots__/limitedReserveTransferSpiritnetHydraDxV2.test.ts.snap
- integration-tests/chopsticks/src/tests/xcm/__snapshots__/limitedReserveTransferSpiritnetHydraDxV3.test.ts.snap
Skipping Rust CI checks since they have not been touched.
> fix: chopstick tests

- Cargo.lock
- pallets/pallet-asset-swap/Cargo.toml
- pallets/pallet-asset-swap/README.md
- pallets/pallet-asset-swap/src/xcm/trade.rs
- pallets/pallet-asset-swap/src/xcm/transfer.rs
The numbers did not match up between what the swap pallet thought the remote balance was, and what the actual remote balance is. This is because there was some dust in the trader `drop()` function we did not handle. That is fixed now, so that whenever a eKILT -> KILT swap happens, the following two things also happen:
1. The amount of remote balance is increased not only by the amount of eKILTs (after XCM fees are taken) being swapped, but also by the amount of fees taken as part of the XCM operation. Now, the real value and the tracked value in the swap pallet always stay consistent.
2. The same corresponding amount of KILTs that are now not swappable because some eKILTs have been used to pay for XCM fees are sent to a configurable account ID (which in the [Peregrine …
> fix: properly handle dust from XCM execution

- Cargo.lock
- pallets/pallet-asset-swap/README.md
- pallets/pallet-asset-swap/src/lib.rs
- pallets/pallet-asset-swap/src/mock.rs
- pallets/pallet-asset-swap/src/traits.rs
- pallets/pallet-asset-swap/src/xcm/transact.rs
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/asset_swap/mod.rs
- runtimes/peregrine/src/lib.rs
WIP.
Based on top of https://github.com/KILTprotocol/kilt-node/pull/659.
Given the current XCM executor logic, specifically the appending of a `ClearOrigin` instruction right after a reserve-based transfer, it is not possible to make any judgments about the origin funds are coming from to our chain, hence it is not possible to apply any restrictions to those.
> feat: support runtime-injected logic for swaps

- Cargo.lock
- pallets/pallet-asset-swap/README.md
- pallets/pallet-asset-swap/src/lib.rs
- pallets/pallet-asset-swap/src/mock.rs
- pallets/pallet-asset-swap/src/traits.rs
- pallets/pallet-asset-swap/src/xcm/match.rs
- pallets/pallet-asset-swap/src/xcm/trade.rs
- pallets/pallet-asset-swap/src/xcm/transact.rs
- pallets/pallet-asset-swap/src/xcm/transfer.rs
- runtime-api/asset-swap/Cargo.toml
- runtime-api/asset-swap/src/lib.rs
- runtimes/peregrine/src/asset_swap/mod.rs
- runtimes/peregrine/src/lib.rs
- runtimes/peregrine/src/xcm_config.rs
Based on top of https://github.com/KILTprotocol/kilt-node/pull/663.
This PR makes it possible for multiple instances of the swap pallet asset to co-exist within the runtime, so that we can implement N:N swaps by deploying multiple pallets (easier solution).
The runtime API has also been updated to take an extra `pair_id` parameter which must match the name of one of the deployed pallets.
> feat: instantiatable swap pallet

- pallets/pallet-asset-switch/README.md
- pallets/pallet-asset-switch/src/xcm/transact/mock.rs
To create holds, a hold reason has to be specified.
> fix: unit tests

- pallets/pallet-asset-switch/src/xcm/transfer/switch_pair_remote_asset/mod.rs
- pallets/pallet-asset-switch/src/xcm/transfer/switch_pair_remote_asset/tests.rs
- pallets/pallet-asset-switch/src/xcm/transfer/xcm_fee_asset/mod.rs
- pallets/pallet-asset-switch/src/xcm/transfer/xcm_fee_asset/tests.rs
Allow funds to make it into our system even if the switch pair is not enabled. If not enabled, they will be trapped later on, but at least we populate the holding registry regardless of the switch pair status.
> fix: IsReserve implementation to allow assets regardless of pool status

- chainspecs/spiritnet/spiritnet.json
This PR adds the Helikon bootnodes to the Kilt Spiritnet chain spec. Helikon nodes can be monitored on both the [Kilt Telemetry](https://telemetry.kilt.io/#/0x411f057b9107718c9624d6aa4a3f23c1653898297f3d4d529d9bb6511a39dd21) and the [W3F Telemetry](https://telemetry.w3f.community/#list/0x411f057b9107718c9624d6aa4a3f23c1653898297f3d4d529d9bb6511a39dd21). You may test the bootnodes using the following command:
```
./kilt-parachain \
--chain spiritnet \
--relay-chain-rpc-urls=wss://rpc.helikon.io/polkadot \
--tmp \
--no-mdns \
--no-telemetry \
--no-hardware-benchmarks \
--reserved-only \
--reserved-nodes "/dns4/boot.helikon.io/tcp/8570/p2p/12D3KooWGaE81VE2rzD5TbeRqpTgQwh2sWXMVfMJLBMHQH8AfoXu"
```
and:
```
./kilt-parachain \
--chain spiritnet \ …
```
> chore: Add Helikon bootnodes.

- .github/workflows/docs-publish.yml
We attempted to create a different github pages branch for every version, but that doesn't work, so to unblock progress for now, this PR switches back to default GitHub way and we will find a better solution soon.
> docs: remove branch auto name for now as it breaks build

- crates/kilt-dip-primitives/src/verifier/parachain/v0/mock.rs
- pallets/did/src/benchmarking.rs
- runtimes/common/src/benchmarks/treasury.rs
Done with `cargo +nightly-2023-10-01 fmt`, the same version used in the CI.
To catch formatting errors locally, the rust-analyzer should be configured to use this toolchain as well.
In `.vscode/settings.json` add the following:
```json
"rust-analyzer.rustfmt.extraArgs": [
"+nightly-2023-10-01"
]
```
> fix: formatting

- .github/workflows/trigger-gitlab-pipeline.yml
- .gitlab-ci.yml
The Gitlab project ID did not need to be a secret, so I made it a repo variable. Everything else seems to work, at least the Pipeline is properly triggered with the latest HEAD.
> fix: gitlab release pipeline

- nodes/parachain/src/chain_spec/mod.rs
Because we match a Peregrine chainspec if the name itself has `peregrine` in it, currently we cannot spin up a Zombienet-based network using Peregrine dev because its name is only `dev`, which would fail to match. I added a second way to generate a peregrine dev chainspec, which is `peregrine-dev`, which contains the word `peregrine` in it, and would allow us to spin up a Zombienet network.
> chore: add peregrine-dev id

- .gitlab-ci.yml
- dip-template/runtimes/dip-consumer/Cargo.toml
- dip-template/runtimes/dip-consumer/src/lib.rs
- dip-template/runtimes/dip-provider/Cargo.toml
- dip-template/runtimes/dip-provider/src/lib.rs
- integration-tests/emulated/Cargo.toml
- nodes/parachain/src/service.rs
- pallets/parachain-staking/Cargo.toml
- pallets/parachain-staking/src/mock.rs
- runtimes/kestrel/Cargo.toml
- runtimes/kestrel/src/lib.rs
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
Making sure our codebase matches steps 1-2 of the [async backing migration guide](https://wiki.polkadot.network/docs/maintain-guides-async-backing).
> fix: async backing

- .github/workflows/trigger-gitlab-pipeline.yml
- .gitlab-ci.yml
I noticed that if we trigger Gitlab pipeline from a tag, the action fails. And if we trigger it from a branch, the Docker image tags are weird. So we should trigger it from a tag from the release branch and from branch (push) from develop and master.
> fix: triggering gitlab pipeline on tags

- Dockerfile
- nodes/parachain/src/chain_spec/mod.rs
- nodes/parachain/src/chain_spec/rilt/mod.rs
- nodes/parachain/src/chain_spec/utils.rs
To avoid runtime panics. Fixes https://github.com/KILTprotocol/ticket/issues/3601 by embedding the well-known chainspecs into the binary. Fixes https://github.com/KILTprotocol/ticket/issues/3597 by defaulting to "peregrine" if a chainspec path is specified that does not contain neither `peregrine` nor `spiritnet`.
> feat: embed chainspecs in binary

- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/types.rs
Implements bonding curve based token burning. Refactors the get_cost associated function to do so.
> feat: implement burn_into extrinsic

- dip-template/runtimes/dip-consumer/Cargo.toml
- dip-template/runtimes/dip-consumer/src/lib.rs
- dip-template/runtimes/dip-provider/Cargo.toml
- dip-template/runtimes/dip-provider/src/lib.rs
- integration-tests/emulated/Cargo.toml
- pallets/parachain-staking/Cargo.toml
- pallets/parachain-staking/src/mock.rs
- runtimes/kestrel/Cargo.toml
- runtimes/kestrel/src/lib.rs
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
Fixes https://github.com/KILTprotocol/ticket/issues/3593.
Removing the feature everywhere and using the pallet implementation without the feature is equivalent to the current solution.
What the aura pallet does without the feature enabled is taking the `MinimumPeriod` as returned by the timestamp pallet, and multiply that by two: see code [here](https://github.com/paritytech/polkadot-sdk/blob/09df373db9cd5dfed82c5cdb0736d417d54249e6/substrate/frame/aura/src/lib.rs#L252).
Everywhere, we set `SlotDuration` to be exactly 2x `MinimumPeriod` (which is 6s), totalling 12s. So basically the net result is that `SlotDuration` is set to `12s` everywhere.
Current values of `MinimuPeriod` are:
* DIP consumer template: https://github.com/KILTprotocol/kilt-node/blob/d9552b70160465eaedd7263db450aa70f49667 …
> chore: remove experimental feature

- .github/workflows/check-code.yml
I chored up the CI file by making sure all jobs (minus the `cargo-test` job) use the same approach:
* Running the whole job INSIDE the Parity-provided Docker container
* Make sure the right cargo path **as configured inside the container** is used to cache cargo artifacts
* Use the `docker run` approach only for the `cargo-test` job, since the worker still runs out of memory and crashes
* Use of `container:` component in all jobs but `cargo-test`
* Use of the `/usr/local/cargo` path for caching cargo artifacts. This is the path configured by the container itself. Using other paths won't have the expected effect.
* Addition of `save-always: true` for the caching of artifacts, since even if, for example a test fails, we still don't want to throw away the compilation work done to run that …
> fix: better caching of Rust deps

- pallets/pallet-asset-switch/src/lib.rs
- pallets/pallet-asset-switch/src/tests/switch.rs
Minor optimisation to prevent users from uselessly spending their tx fees.
> fix: bail out early if switching zero amount

- pallets/attestation/src/lib.rs
- pallets/attestation/src/tests/deposit.rs
- pallets/delegation/src/lib.rs
- pallets/delegation/src/mock.rs
- pallets/delegation/src/tests/deposit.rs
- pallets/did/src/lib.rs
- pallets/did/src/tests/deposit.rs
- pallets/pallet-did-lookup/src/lib.rs
- pallets/pallet-did-lookup/src/mock.rs
- pallets/pallet-did-lookup/src/tests/deposit.rs
- pallets/pallet-web3-names/src/lib.rs
- pallets/pallet-web3-names/src/mock.rs
- pallets/pallet-web3-names/src/tests/claim.rs
- pallets/pallet-web3-names/src/tests/deposit.rs
- pallets/public-credentials/src/lib.rs
- pallets/public-credentials/src/mock.rs
- pallets/public-credentials/src/tests/claim.rs
- pallets/public-credentials/src/tests/deposit.rs
- support/src/traits.rs
Fixes https://github.com/KILTprotocol/ticket/issues/3074.
Cc @kilted-andres 
I tried to keep the event structure in all pallets the same, with the same name and the same fields `id`, `from` and `to`. The `id` field has a different type depending on the pallet, but the `from` and `to` are all the same.
> chore: add events for deposit owner changes

- Cargo.lock
Cargo deny was complaining. This bumps all `futures*` crates from `0.30.0` to `0.30.1`.
> chore: bump yanked dependency

- chainspecs/spiritnet/spiritnet.json
Includes https://github.com/KILTprotocol/kilt-node/pull/749 and https://github.com/KILTprotocol/kilt-node/pull/745/ and removes OnFinality bootnodes.
> chore: update chainspec

- zombienet/README.md
Fixes https://github.com/KILTprotocol/ticket/issues/3633.
Pick any version of Polkadot or Paseo, and try following the steps in the README. See if the network starts running.
> chore: add Zombienet docs

- pallets/pallet-bonded-coins/Cargo.toml
- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/mock.rs
- pallets/pallet-bonded-coins/src/traits.rs
- pallets/pallet-bonded-coins/src/types.rs
> chore: mocks for bonding curve pallet

- dip-template/runtimes/dip-provider/src/lib.rs
- pallets/pallet-did-lookup/src/lib.rs
- pallets/pallet-did-lookup/src/mock.rs
- pallets/pallet-did-lookup/src/tests/associate.rs
- pallets/pallet-did-lookup/src/try_state.rs
- pallets/pallet-dip-consumer/src/mock.rs
- pallets/pallet-migration/src/mock.rs
- runtimes/common/src/dip/mock.rs
- runtimes/kestrel/src/lib.rs
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/src/lib.rs
Part of https://github.com/KILTprotocol/ticket/issues/3650. Built on top of https://github.com/KILTprotocol/kilt-node/pull/781.
I chose to go this way instead of providing an optional counter, because providing a counter would require one of the following two approaches:
1. Transform the storage double map into a counted one, requiring a migration also for our currently-deployed pallet, which I wanted to avoid
2. Not use a counter, but iterate every time to make sure there are still "spots" left for the current DID. This would require changing the benchmarking logic as now we have a potentially unbounded iteration happening. I also wanted to avoid that.
Hence, the solution was to provide a somehow more limited feature of simply specifying whether the links are expected to be unique per …
> feat: support for unique linking

- Cargo.lock
- Cargo.toml
- dip-template/runtimes/dip-provider/src/lib.rs
- runtime-api/did/src/lib.rs
- runtime-api/unique-linking/Cargo.toml
- runtime-api/unique-linking/src/lib.rs
- runtimes/common/src/errors.rs
- runtimes/kestrel/src/lib.rs
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/src/lib.rs
Part of https://github.com/KILTprotocol/ticket/issues/3650, based on top of https://github.com/KILTprotocol/kilt-node/pull/784. Last bit of required functionality.
* Since it's not possible to batch multiple runtime API calls, I introduced a `batch_` version for our old `did` runtime API, which allows to do batching instead of firing one request per lookup
* Similarly to that, I introduced a new runtime API (since it's not possible to implement the same API twice for the same runtime), which resolves an account given a name, or a name given an account. This new API also provides a batched version to resolve multiple names or addresses at once. This was one of the requirements we got from Parity to make the solution easier to integrate in the mobile app
Polkadot Apps support new runtime …
> feat: new runtime API for unique linking

- pallets/pallet-bonded-coins/src/mock.rs
- pallets/pallet-bonded-coins/src/tests/transactions/create_pool.rs
- pallets/pallet-bonded-coins/src/tests/transactions/mod.rs
- pallets/pallet-bonded-coins/src/tests/transactions/reset_manager.rs
- pallets/pallet-bonded-coins/src/tests/transactions/reset_team.rs
Adds unit tests for changing/resetting pool manager and asset (admin) team.
To be rebased and merged after https://github.com/KILTprotocol/kilt-node/pull/785
Tests currently failing (fix TBD in another PR):
> test: reset manager and team

- .cargo-deny.toml
The CI started failing because a Substrate dependency has gone officially unmaintained. We start ignoring that dependency and will re-evaluate at the next polkadot-sdk upgrade what to do.
> chore: update cargo-deny file

- pallets/pallet-bonded-coins/src/curves/mod.rs
- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/tests/curves/arithmetic.rs
I realised that scaling may be done more elegantly and less likely to overflow by using a U256 to implement what essentially amounts to direct division on a fixed point number with >= 128 integer bits. This way the only overflow we can get is when the result (the scaled value) is too large to fit into the target type. 
In other words, the scaling logic is infallible, with the only error case being that the scaling factor is too small, so that the result cannot be represented.
I wanted to ask for your opinion on this solution before I apply it to my pending PR.    
> refactor: use U256 for infallible scaling

- pallets/pallet-bonded-coins/src/curves/mod.rs
- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/mock.rs
- pallets/pallet-bonded-coins/src/tests/curves/arithmetic.rs
- pallets/pallet-bonded-coins/src/tests/curves/mod.rs
Adresses issues with precision stemming from integer division in `convert_to_fixed` and suggests a strategy to mitigate overflow problems on `refund_account`.
> fix: denomination arithmetic

- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/mock.rs
- pallets/pallet-bonded-coins/src/tests/transactions/burn_into.rs
- pallets/pallet-bonded-coins/src/tests/transactions/create_pool.rs
- pallets/pallet-bonded-coins/src/tests/transactions/mint_into.rs
- pallets/pallet-bonded-coins/src/tests/transactions/reset_team.rs
Adds unit tests for burning and minting. Tests document _EXPECTED_ behaviour, which currently differs from the actual behaviour in a lot of places.
Currently failing:
- mint_into::mint_first_coin
- Fails due to flooring of amount_to_mint during conversion to float; may be fixed by proper rounding, or ignored by changing the assertion to an `assert_eq_error_rate!` with error `1`.
- mint_into::mint_in_refunding_pool
- Should give `PoolNotLive` error but yields `NoPermission` 
- mint_into::mint_large_quantity
- Fails because we overflow when converting large amounts of collateral back to a u128. Can be fixed with conversion logic similar to the conversion to fixed. 
- mint_into::multiple_mints_vs_combined_mint
- fails due to imprecision - not clear if this can be resolved 
- …
> test: mint and burn

- pallets/pallet-bonded-coins/src/tests/transactions/set_lock.rs
- pallets/pallet-bonded-coins/src/tests/transactions/unlock.rs
Implements unit tests for `set_lock` & `unlock`.
> test: lock/unlock

- pallets/pallet-bonded-coins/src/mock.rs
- pallets/pallet-bonded-coins/src/tests/transactions/finish_destroy.rs
- pallets/pallet-bonded-coins/src/tests/transactions/mod.rs
- pallets/pallet-bonded-coins/src/tests/transactions/start_destroy.rs
- pallets/pallet-bonded-coins/src/types.rs
Tests the three destruction extrinsics. All tests passing rn.
To be rebased after merging #791.
> test: destroy

- pallets/pallet-bonded-coins/src/benchmarking.rs
- pallets/pallet-bonded-coins/src/curves/mod.rs
- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/tests/curves/arithmetic.rs
Unties the utility functions performing scaled conversion from a balance type to a fixed (and back) from the pallet config trait.
This also allows us to easily drop the requirement that the bonded coins and collateral need to use the same balance type.
Finally, I made sure that the symmetry of the two functions is reflected in their names and parameter order.
> refactor: decouple balance to fixed from config

- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/mock.rs
- pallets/pallet-bonded-coins/src/traits.rs
Based on the discussion: https://github.com/KILTprotocol/kilt-node/pull/818#discussion_r1869222126, we have to check whether the `NextAssetIds` hook is returning the right amount of asset ids.
> fix: check return asset ids from hook

- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/mock.rs
- pallets/pallet-bonded-coins/src/tests/transactions/burn_into.rs
- pallets/pallet-bonded-coins/src/tests/transactions/create_pool.rs
- pallets/pallet-bonded-coins/src/tests/transactions/finish_destroy.rs
- pallets/pallet-bonded-coins/src/tests/transactions/mint_into.rs
- pallets/pallet-bonded-coins/src/tests/transactions/refund_account.rs
- pallets/pallet-bonded-coins/src/tests/transactions/reset_manager.rs
- pallets/pallet-bonded-coins/src/tests/transactions/reset_team.rs
- pallets/pallet-bonded-coins/src/tests/transactions/set_lock.rs
- pallets/pallet-bonded-coins/src/tests/transactions/start_destroy.rs
- pallets/pallet-bonded-coins/src/tests/transactions/start_refund.rs
- pallets/pallet-bonded-coins/src/tests/transactions/unlock.rs
- pallets/pallet-bonded-coins/src/try_state.rs
I removed one test that was breaking the pallet's invariant.
The state of the bonded currencies cannot be queried, nor can the accounts holding funds.
> chore: try runtime

- dip-template/runtimes/dip-provider/src/lib.rs
- pallets/did/src/origin.rs
- pallets/pallet-did-lookup/src/benchmarking.rs
- pallets/pallet-did-lookup/src/lib.rs
- pallets/pallet-did-lookup/src/mock.rs
- pallets/pallet-dip-consumer/src/mock.rs
- pallets/pallet-migration/src/mock.rs
- pallets/pallet-web3-names/src/benchmarking.rs
- pallets/pallet-web3-names/src/lib.rs
- pallets/pallet-web3-names/src/mock.rs
- runtimes/common/Cargo.toml
- runtimes/common/src/dip/mock.rs
- runtimes/common/src/dot_names/mod.rs
- runtimes/common/src/dot_names/origin.rs
- runtimes/kestrel/src/lib.rs
- runtimes/peregrine/src/kilt/did.rs
- runtimes/spiritnet/src/kilt/did.rs
Fixes https://github.com/KILTprotocol/ticket/issues/3691.
This PR allows to dynamically (i.e., via the sudo origin) elect an account as the only authorised to submit `claim` extrinsic for any web3name pallet deployment, and `associate_account` and `associate_sender` extrinsics for any did-lookup deployment. 
I also updated our dotnames and unique linking deployments for both our runtimes to use this new feature, althought I had to rely on a trick with `storage_alias`es to avoid introducing a new pallet just for this. Unfortunately, the [pallet-parameters](https://github.com/paritytech/polkadot-sdk/tree/master/substrate/frame/parameters) was only introduced in 1.8.0, so we might want to migrate to using that once we update our codebase to 1.8.0. For now, I could not think of any other way …
> feat: support gatekeeping web3names and account linkings

- pallets/pallet-deposit-storage/src/deposit/mock.rs
- pallets/pallet-deposit-storage/src/deposit/tests/on_commitment_removed.rs
- pallets/pallet-deposit-storage/src/deposit/tests/on_identity_committed.rs
- pallets/pallet-deposit-storage/src/fungible/mod.rs
- pallets/pallet-deposit-storage/src/fungible/tests/burn.rs
- pallets/pallet-deposit-storage/src/fungible/tests/hold.rs
- pallets/pallet-deposit-storage/src/fungible/tests/inspect_hold.rs
- pallets/pallet-deposit-storage/src/fungible/tests/mock.rs
- pallets/pallet-deposit-storage/src/fungible/tests/release.rs
- pallets/pallet-deposit-storage/src/fungible/tests/transfer.rs
- pallets/pallet-deposit-storage/src/fungible/try_state.rs
- pallets/pallet-deposit-storage/src/lib.rs
- pallets/pallet-deposit-storage/src/mock.rs
- pallets/pallet-deposit-storage/src/tests/add_deposit.rs
- pallets/pallet-deposit-storage/src/tests/reclaim_deposit.rs
- pallets/pallet-deposit-storage/src/try_state.rs
Based on top of https://github.com/KILTprotocol/kilt-node/pull/823.
It adds `try-runtime` checks for both the `MutateHold` implementation as well as the rest of the deposits, so that one feature does not interfere with the other.
> test: add try-state tests for pallet-deposit-storage

- .gitlab-ci.yml
- Cargo.lock
- Cargo.toml
- runtimes/peregrine/Cargo.toml
- runtimes/peregrine/build.rs
- runtimes/peregrine/src/lib.rs
- runtimes/spiritnet/Cargo.toml
- runtimes/spiritnet/build.rs
- runtimes/spiritnet/src/lib.rs
We introduce a new feature for peregrine and spiritnet runtimes, which adds the metadata hash signed extension, for wallets that need it.
The Gitlab build pipeline has also been updated to include the new feature only when building the production WASMs.
Change any integration tests in the SDK based on this PR (https://github.com/KILTprotocol/sdk-js/pull/924), and verify the metadata is verified (e.g., by enabling logs via a Chopsticks deployment).
> feat: add support for metadata hash checks

- Cargo.lock
- nodes/standalone/Cargo.toml
- runtimes/kestrel/Cargo.toml
- runtimes/kestrel/build.rs
- runtimes/kestrel/src/lib.rs
The node is used in SDK integration tests, so we need to have it in there to make sure having support for it works fine.
> feat: add metadata hash check also for standalone node

- .maintain/build-image.sh
The `Organisation` was missing from the docker tag
> ci: fix tag

- pallets/did/src/origin.rs
- runtimes/common/src/dot_names/origin.rs
Right now, if the new runtime is enacted and there's no authorised account set, the calls are considered permissionless. To avoid this, and to allow us to set an account later on, I changed the logic so that by default it's considered unusable, and only when an account is set, the stored account is checked. I introduced also a new type to allow for permissionless dispatch.
The change does not require any migrations or changes to storage, as it simply introduces a semantic change to how those storage values are interpreted.
Use chopsticks to try to claim a DOT name before anything is set, it will fail with `BadOrigin`. Set the new value with a `sudo.setStorage` call, and verify that only that account can submit `dotname.claim` or `uniqueLinking.linkAccount` transactions.
> feat: change gatekeeping logic to avoid complex deployment setups

- pallets/pallet-bonded-coins/src/lib.rs
The pool_id is based on the bonded currency IDs. If you attempt to create a pool twice without associating any bonded currencies, the pool_id will collide, resulting in an internal error.
> fix: ensure at least one currency in pool

- pallets/attestation/src/lib.rs
In SCALE encoding, the struct name is irrelevant for the encoding, only the order matters. By changing the order of the properties in the events, we can hopefully reduce the amount of breaking changes.
> chore: change struct order

- runtimes/peregrine/src/kilt/did/mod.rs
- runtimes/spiritnet/src/kilt/did/mod.rs
The current benchmark logic does not work for the DOT names and unique linking pallets.
For now, the issue is mitigated by implementing a feature-guided configuration. Ideally, the BenchmarkHelper should handle setting up the required storage. [#3756](https://github.com/KILTprotocol/ticket/issues/3756)
> fix: benchmark configuration runtime

- runtimes/common/src/migrations.rs
- runtimes/peregrine/src/migrations/mod.rs
- runtimes/spiritnet/src/migrations/mod.rs
I added the required migration for the new deployments, and made the `BumpStorageVersion` type a bit more generic to work with any pallets that might need the same treatment in the future.
I tried the new migrations with both Peregrine (new runtime) and Spiritnet (previous runtime), and I got no errors.
> fix: add required migration

- scripts/run_benches_for_runtime.sh
Fixes the benchmark scripts. The unique-linking and dot-names pallet do not exist anymore.
> fix: benchmarks script

- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/mock.rs
- pallets/pallet-bonded-coins/src/tests/transactions/refund_account.rs
Adopts the recommended resolution and checks for the reason of the `can_deposit` check failing. Funds (in bonded coins) are only destroyed if there is a `BelowMinimum` error, which indicates that the account to which the deposit should be send cannot be created because the amount is too low. This scenario can be tolerated, as this amount will likely have negligible financial value.
Other error cases will not lead to the destruction of funds, which means that in theory a refunding pool may not be able to fully refund because some account does not meet criteria for receiving funds. This can include: 
- The maximum amount of Consumer references is exhausted
- The Provider references counter would overflow
- The collateral currency is frozen
* Either PR or Ticket to update [the …
> fix: only destroy funds on refund if collateral is BelowMinimum

- crates/kilt-dip-primitives/src/merkle_proofs/v0/provider_state/tests.rs
- crates/kilt-dip-primitives/src/verifier/parachain/v0/mock.rs
- pallets/attestation/src/mock.rs
- pallets/ctype/src/mock.rs
- pallets/delegation/src/mock.rs
- pallets/did/src/mock.rs
- pallets/pallet-asset-switch/src/mock.rs
- pallets/pallet-bonded-coins/src/mock.rs
- pallets/pallet-configuration/src/mock.rs
- pallets/pallet-deposit-storage/src/deposit/mock.rs
- pallets/pallet-deposit-storage/src/fungible/tests/mock.rs
- pallets/pallet-deposit-storage/src/mock.rs
- pallets/pallet-did-lookup/src/mock.rs
- pallets/pallet-dip-consumer/src/mock.rs
- pallets/pallet-dip-provider/src/mock.rs
- pallets/pallet-inflation/src/mock.rs
- pallets/pallet-migration/src/mock.rs
- pallets/pallet-relay-store/src/mock.rs
- pallets/pallet-web3-names/src/mock.rs
- pallets/parachain-staking/src/mock.rs
- pallets/public-credentials/src/mock.rs
- runtimes/common/src/dip/deposit/mock.rs
- runtimes/common/src/dip/mock.rs
- runtimes/common/src/fees.rs
- runtimes/kestrel/src/lib.rs
- runtimes/peregrine/src/system/mod.rs
- runtimes/spiritnet/src/system/mod.rs
Increases consumers limits to 100 for peregrine, spiritnet, mocks & tests.
Configs for dip-templates are left as-is.
It's hard for me to tell if this is going to have an impact on benchmarking / transaction weights though, how can we check this?
> fix: increase MaxConsumers to allow accounts to hold more than 15 different bonded coins

- pallets/pallet-bonded-coins/src/benchmarking.rs
- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/tests/transactions/reset_team.rs
Changes the `reset_team` extrinsic to perform batch updates in order to avoid that asset management teams differ between assets of one pool.
Recommended by auditors and desired by our team - see linked ticket.
> refactor: batch updating of asset team

- pallets/pallet-bonded-coins/src/benchmarking.rs
- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/tests/transactions/create_pool.rs
Disallows re-using the same token symbol or name. Empty names and symbols are always allowed.
> feat: disallow re-using token names and symbols within a pool

- pallets/pallet-bonded-coins/src/benchmarking.rs
- pallets/pallet-bonded-coins/src/tests/transactions/reset_team.rs
- pallets/pallet-bonded-coins/src/traits.rs
Changes the reset_team trait to actually set the owner passed to the function.
The trait implementation is a back-port of a trait implemented in latest versions of pallet-assets (https://docs.rs/pallet-assets/41.0.0/pallet_assets/pallet/struct.Pallet.html#impl-ResetTeam%3C%3CT+as+Config%3E::AccountId%3E-for-Pallet%3CT,+I%3E). Changing ownership of an asset is part of this trait but was not implemented here as not needed.
Nevertheless, we're adding this now to avoid mismatched expectations.
> fix: make sure the reset_team trait actually sets the owner

- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/tests/transactions/set_lock.rs
- pallets/pallet-bonded-coins/src/types.rs
> fix: do not allow lock states that are equivalent to unlocked

- pallets/pallet-bonded-coins/src/lib.rs
Disallows manager changes after a pool has been moved to refunding or destroying.
> fix: prohibit manager changes on non-live pools

- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/tests/transactions/reset_team.rs
Following recommendations by OAK, this adds another event to be emitted on calling `reset_team`. This is emitted in addition to the events emitted by the assets pallet itself.
> feat: emit additional event on reset_team

- pallets/pallet-bonded-coins/src/benchmarking.rs
- pallets/pallet-bonded-coins/src/lib.rs
- pallets/pallet-bonded-coins/src/mock.rs
- pallets/pallet-bonded-coins/src/tests/transactions/burn_into.rs
- pallets/pallet-bonded-coins/src/tests/transactions/create_pool.rs
- pallets/pallet-bonded-coins/src/tests/transactions/reset_team.rs
- pallets/pallet-bonded-coins/src/try_state.rs
- pallets/pallet-bonded-coins/src/types.rs
- runtime-api/bonded-coins/src/pool_details.rs
- runtimes/common/src/constants.rs
- runtimes/peregrine/src/runtime_apis.rs
Addresses potential centralisation concerns around manager permissions. Having this additional flag could make the extent of centralisation of powers in a pool more transparent. If it is set to `false` the reset_team() transaction cannot be used on this pool, in which case the manager has much more limited privileges (locking/unlocking and initiating refunding). This flag can only be set on pool creation and not changed.
> feat: flag to disallow asset management changes

- integration-tests/chopsticks/src/tests/switchPallet/fullFlow/config.ts
- integration-tests/chopsticks/src/tests/switchPallet/switchConfig/failingOnReceiver/__snapshots__/index.test.ts.snap
- integration-tests/chopsticks/src/tests/switchPallet/switchConfig/failingOnReceiver/config.ts
- integration-tests/chopsticks/src/tests/switchPallet/switchConfig/noSwitchPair/__snapshots__/index.test.ts.snap
- integration-tests/chopsticks/src/tests/switchPallet/switchConfig/noSwitchPair/config.ts
- integration-tests/chopsticks/src/tests/switchPallet/switchConfig/otherReserveLocation/__snapshots__/index.test.ts.snap
- integration-tests/chopsticks/src/tests/switchPallet/switchConfig/otherReserveLocation/config.ts
We decided to remove the `messageQueue` pallet from the snapshot tests since its events are not reliably reproducible and cause flaky tests. This PR removes all occurrences.
> fix: remove messageQueue

- Cargo.lock
__RUSTSEC-2025-0009__ is fixed on `ring >= 0.17.12`, we are still using `0.17.8`
> chore(deps): update ring

- Cargo.lock
Cargo deny raises warnings about an issue in the Tokyo library, which has soundness issues in the version used here.
Fortunately this can easily be bumped to a patched version.
> chore(deps): bump tokio due to RUSTSEC-2025-0023
